---
title: "writing_functions"
author: "Dantong Zhu"
date: "2021/11/4"
output: github_document
---

```{r}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Z-score
```{r}
x_vec = rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

z_scores = function(x){
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)

z_scores(y_vec) ##name input; also unneccessary
```


how great is this?
```{r, error=TRUE}
#evaluate the type of x
z_scores = function(x){
  
  if(!is.numeric(x)) {
    stop("x needs to be numeric") 
  }
  
  if(length(x) < 3){
    stop("x should have at least 3 numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(3)

z_scores(c("my","name"))

z_scores(mtcars)
```


# Multiple outputs
```{r}
mean_sd = function(x){
  
  if(!is.numeric(x)) {
    stop("x needs to be numeric") 
  }
  
  if(length(x) < 3){
    stop("x should have at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = 
    tibble(
      mean_x = mean(x),
      sd_x = sd(x)
    )
    
    return(output_df)

}
mean_sd(x_vec)
mean_sd(y_vec)
```


## Different sample sizes, means, sds
```{r}
sim_data = 
  tibble(
    x = rnorm(30, mean = 2, sd =3)
  )

sim_data %>% 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )

```

let's write function simulating data, computing the mean and sd
```{r}
sim_mean_sd = function(n, mu, sigma){
  
  # do checks on inputs
  
sim_data = 
tibble(
  x = rnorm(mu, mean = mu, sd = sigma)
)

sim_data %>% 
summarise(
  mean = mean(x),
  sd = sd(x)
)
}

sim_mean_sd(30,4,3)
#position matching in（）
```


